USE RWS_DB;
DROP TABLE IF EXISTS `CIRCLES`;
DROP TABLE IF EXISTS `TRIANGLES`;
DROP TABLE IF EXISTS `RECTANGLES`;
DROP TABLE IF EXISTS `SHAPES`;

CREATE TABLE `SHAPES` (
`SHAPE_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`SHAPE_SQUARE` FLOAT(10,2) UNSIGNED NOT NULL,
PRIMARY KEY (`SHAPE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `CIRCLES` (
`SHAPE_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`CIRCLE_RADIUS` INT(10) UNSIGNED NOT NULL,
PRIMARY KEY (`SHAPE_ID`),
FOREIGN KEY (`SHAPE_ID`)
REFERENCES `SHAPES`(`SHAPE_ID`)
ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `TRIANGLES` (
`SHAPE_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`TRIANGLE_BASE` INT(10) UNSIGNED NOT NULL,
`TRIANGLE_HEIGHT` INT(10) UNSIGNED NOT NULL,
PRIMARY KEY (`SHAPE_ID`),
FOREIGN KEY (`SHAPE_ID`)
REFERENCES `SHAPES`(`SHAPE_ID`)
ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `RECTANGLES` (
`SHAPE_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`RECTANGLE_WIDTH` INT(10) UNSIGNED NOT NULL,
`RECTANGLE_LENGTH` INT(10) UNSIGNED NOT NULL,
PRIMARY KEY (`SHAPE_ID`),
FOREIGN KEY (`SHAPE_ID`)
REFERENCES `SHAPES`(`SHAPE_ID`)
ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
